/**
 * Familias de palabras de la sección "Palabras de vida".
 *
 * Regla: una familia = una palabra y las que salen de su MISMA raíz (amor, amar, amado…).
 * Los sinónimos NO se suman: "miedo" y "temor" son dos palabras distintas, cada una con su cuenta.
 *
 * Cada entrada: [id, palabra que se muestra, patrones, formas excluidas].
 * - Los patrones se prueban contra cada palabra del versículo, completa y en minúsculas.
 * - Las formas excluidas calzan con el patrón pero casi siempre significan otra cosa en la Biblia
 *   (ej. "amo" = dueño, no "yo amo"; "creó" = hizo, no "creyó").
 *
 * Quedan fuera a propósito: artículos y palabras de relleno, nombres propios, lugares, cargos
 * (rey, sacerdote) y cosas sin mensaje para la vida (ejército, oro, ciudad…).
 * El generador ordena por repeticiones y toma las 100 primeras.
 */
const PRON = '(me|te|se|lo|la|le|los|las|les|nos)?'
const AR = `ar|o|as|a|amos|an|é|aste|ó|aron|aba|abas|aban|ábamos|aré|arás|ará|aremos|arán|aría|arían|e|es|emos|en|ara|aras|aran|ase|asen|ando|ado|ada|ados|adas|ad|ar${PRON}|ándo${PRON}|a${PRON}|e${PRON}|en${PRON}`
const ER = `er|o|es|e|emos|en|í|iste|ió|imos|ieron|ía|ías|ían|íamos|eré|erás|erá|eremos|erán|ería|erían|a|as|amos|an|iera|ieras|ieran|iese|iendo|ido|ida|idos|idas|ed|er${PRON}|iéndo${PRON}`
const IR = `ir|o|es|e|imos|en|í|iste|ió|ieron|ía|ías|ían|íamos|iré|irás|irá|iremos|irán|iría|irían|a|as|amos|an|iera|ieras|ieran|iese|iendo|ido|ida|idos|idas|id|ir${PRON}|iéndo${PRON}`
const ar = raiz => new RegExp(`^${raiz}(${AR})$`)
const er = raiz => new RegExp(`^${raiz}(${ER})$`)
const ir = raiz => new RegExp(`^${raiz}(${IR})$`)

module.exports = [
  // ── Dios ──
  ['senor', 'Señor', [/^señor(es)?$/], []],
  ['dios', 'Dios', [/^dios$/, /^divin[oa]s?$/], []],
  ['jesus', 'Jesús', [/^jesús$/], []],
  ['cristo', 'Cristo', [/^cristo$/, /^jesucristo$/, /^mesías$/, /^cristian[oa]s?$/], []],

  // ── Vida, muerte y eternidad ──
  ['vida', 'Vida', [/^vidas?$/, /^viv(ir|o|a|os|as|e|es|en|imos|an|amos|iré|irás|irá|iremos|irán|iente|ientes|ific\w+)$/], []],
  ['muerte', 'Muerte', [/^muertes?$/, /^muert[oa]s?$/, /^mor(ir|iré|irás|irá|iremos|irán|ía|ían|imos|iría|irían|irse|irme|tal|tales)$/, /^mur(ió|ieron|iendo|iera|ieran|iese)$/, /^muer(o|es|e|en|a|as|an)$/], []],
  ['eternidad', 'Eternidad', [/^etern[oa]s?$/, /^eternamente$/, /^eternidad$/], []],
  ['resurreccion', 'Resurrección', [/^resurrec\w+$/, /^resucit\w+$/], []],
  ['cielo', 'Cielo', [/^cielos?$/, /^celestial(es)?$/], []],
  ['alma', 'Alma', [/^almas?$/], []],
  ['espiritu', 'Espíritu', [/^esp[ií]ritus?$/, /^espiritual(es|mente)?$/], []],
  ['corazon', 'Corazón', [/^coraz(ón|ones)$/], []],
  ['cuerpo', 'Cuerpo', [/^cuerpos?$/], []],
  ['sangre', 'Sangre', [/^sangres?$/, /^sangrient\w+$/], []],
  ['tiempo', 'Tiempo', [/^tiempos?$/], []],
  ['mundo', 'Mundo', [/^mundos?$/], []],
  ['creacion', 'Creación', [/^creaci(ón|ones)$/, /^creador$/, /^criaturas?$/, /^cre(ó|ar|ado|ada|ados|adas|aste|aré|ará)$/], []],

  // ── Fe, esperanza y amor ──
  ['amor', 'Amor', [/^amor(es)?$/, ar('am'), /^ám[ea](me|te|se|lo|la|los|las|nos|nse)$/, /^amoros[oa]s?$/], ['amo', 'amos', 'amas', 'ama']],
  ['fe', 'Fe', [/^fe$/, /^fiel(es)?$/, /^fidelidad$/, /^fielmente$/], []],
  ['creer', 'Creer', [er('cre'), /^crey(ó|eron|endo|ente|entes|era|eran)$/, /^cre(ído|ída|ímos|íste)$/, /^incrédul\w+$/, /^incredulidad$/], ['crea', 'creas', 'creo']],
  ['esperanza', 'Esperanza', [/^esperanzas?$/, ar('esper')], []],
  ['confianza', 'Confianza', [/^confianza$/, /^conf(iar|ío|ías|ía|iamos|ían|ié|ió|iaron|iaba|iaban|iaré|iará|iarán|íe|íes|íen|iemos|iando|iado|iada|iados|iadas|iad)$/, /^confí(a|e|en)(me|te|se|le|les|nos)?$/], []],
  ['caridad', 'Compasión', [/^compasi(ón|v[oa]s?)$/, /^compade\w+$/], []],
  ['misericordia', 'Misericordia', [/^misericordi\w+$/], []],
  ['bondad', 'Bondad', [/^bondad(es)?$/, /^bondados[oa]s?$/, /^buen(o|a|os|as)?$/], []],
  ['gracia', 'Gracia', [/^gracia$/], []],
  ['gratitud', 'Gratitud', [/^gracias$/, /^agradec\w+$/, /^agradez\w+$/, /^gratitud$/], []],
  ['perdon', 'Perdón', [/^perd(ón|ones)$/, ar('perdon'), /^perdón(a|e|en)(me|nos|lo|la|los|las|le|les)$/], []],
  ['paz', 'Paz', [/^paz$/, /^pac[ií]fic[oa]s?$/, /^pacíficamente$/], []],
  ['alegria', 'Alegría', [/^alegr[ií]as?$/, /^alegres?$/, ar('alegr'), /^alégr(ate|ense|ese|aos|émonos)$/], []],
  ['gozo', 'Gozo', [/^gozos?$/, /^gozos[oa]s?$/, ar('goz'), /^regocij\w+$/], []],
  ['felicidad', 'Felicidad', [/^feli(z|ces|cidad)$/, /^dichos[oa]s?$/, /^dicha$/], []],
  ['consuelo', 'Consuelo', [/^consuel\w+$/, /^consol\w+$/], ['consolidó', 'consolidar', 'consolidado']],
  ['humildad', 'Humildad', [/^humild\w+$/, /^humill\w+$/], []],
  ['paciencia', 'Paciencia', [/^pacien\w+$/], []],
  ['generosidad', 'Generosidad', [/^generos\w+$/], []],
  ['ayuda', 'Ayuda', [/^ayudas?$/, ar('ayud'), /^ayúd(a|e|en)(me|nos|lo|la|los|las|le|les)$/], []],

  // ── Dios y su obra ──
  ['salvacion', 'Salvación', [/^salvaci(ón|ones)$/, /^salvador(a|es)?$/, ar('salv'), /^sálva(me|nos|lo|los|la|las|te)$/], ['salvo']],
  ['bendicion', 'Bendición', [/^bendici(ón|ones)$/, /^bend(ecir|igo|ices|ice|ecimos|icen|ije|ijo|ijeron|ecía|ecían|eciré|ecirá|ecirán|iga|igas|igan|igamos|iciendo|ecido|ecida|ecidos|ecidas)$/, /^bendit[oa]s?$/, /^bend(ecir|íce|íga|ígan)(me|te|lo|la|los|las|nos|le|les)$/], []],
  ['gloria', 'Gloria', [/^glorias?$/, /^glorios[oa]s?$/, /^glorific\w+$/, /^gloriar\w*$/], []],
  ['santidad', 'Santidad', [/^sant[oa]s?$/, /^santidad$/, /^santific\w+$/, /^santísim[oa]$/], []],
  ['reino', 'Reino', [/^reinos?$/], []],
  ['alianza', 'Alianza', [/^alianzas?$/], []],
  ['promesa', 'Promesa', [/^promesas?$/, /^promet\w+$/], []],
  ['palabra', 'Palabra', [/^palabras?$/], []],
  ['ley', 'Ley', [/^ley(es)?$/], []],
  ['mandamiento', 'Mandamientos', [/^mandamientos?$/, /^mandatos?$/], []],
  ['voluntad', 'Voluntad', [/^voluntad(es)?$/, /^voluntari\w+$/], []],
  ['poder', 'Poder', [/^poder(es)?$/, /^poderos[oa]s?$/, /^todopoderoso$/], []],
  ['milagro', 'Milagros', [/^milagr\w+$/], []],
  ['senal', 'Señales', [/^señal(es)?$/], []],
  ['maravilla', 'Maravillas', [/^maravill\w+$/], []],
  ['luz', 'Luz', [/^lu(z|ces)$/], []],
  ['oscuridad', 'Oscuridad', [/^oscur\w+$/, /^tinieblas?$/], []],
  ['camino', 'Camino', [/^caminos?$/], []],
  ['verdad', 'Verdad', [/^verdad(es)?$/, /^verdader[oa]s?$/, /^verdaderamente$/], []],
  ['sabiduria', 'Sabiduría', [/^sabidur[ií]as?$/, /^sabi[oa]s?$/, /^sabiamente$/], []],
  ['conocimiento', 'Conocimiento', [/^conocimiento\w*$/, /^conoc(er|e|en|es|emos|í|ió|ieron|ía|ían|erá|erán|eré|ido|ida|idos|iendo)$/, /^conozc\w+$/], []],
  ['entendimiento', 'Entendimiento', [/^entendimiento$/, /^entend\w+$/, /^entiend\w+$/, /^inteligen\w+$/], []],
  ['ensenanza', 'Enseñanza', [/^enseñ\w+$/], []],
  ['consejo', 'Consejo', [/^consej\w+$/, /^aconsej\w+$/], []],
  ['presencia', 'Presencia', [/^presencia$/], []],
  ['angel', 'Ángeles', [/^ángel(es)?$/], []],
  ['cruz', 'Cruz', [/^cru(z|ces)$/, /^crucific\w+$/, /^crucifi\w+$/], []],
  ['redencion', 'Rescate', [/^rescat\w+$/, /^redim\w+$/, /^redenci\w+$/, /^redentor$/], []],
  ['libertad', 'Libertad', [/^libertad(es)?$/, /^libres?$/, /^liber(ar|a|an|ó|aron|ará|arán|aré|ado|ada|ados|adas|e|en|tador|ación)$/, /^libr(ar|a|an|ó|aron|ará|arán|aré|aba|ado|ada|ados|adas|e|en)$/, /^líbra(me|nos|lo|los)$/], []],
  ['victoria', 'Victoria', [/^victori\w+$/, /^venc(er|e|en|ió|ieron|erá|erán|eré|ido|idos|ida|edor|edores|imos)$/], []],
  ['herencia', 'Herencia', [/^herenc\w+$/, /^hered\w+$/], []],
  ['eleccion', 'Elección', [/^elegid[oa]s?$/, /^eleg(ir|í|iste|imos)$/, /^elig(ió|ieron|e|en|es)$/, /^elij\w+$/, /^escog\w+$/, /^escoj\w+$/, /^elecci\w+$/], []],

  ['mensaje', 'Mensaje', [/^mensajes?$/, /^mensajer[oa]s?$/], []],
  ['voz', 'Voz', [/^vo(z|ces)$/], []],
  ['enviar', 'Envío', [/^envi(ar|o|as|a|amos|an|é|aste|ó|aron|aba|aban|aré|ará|arán|ado|ada|ados|adas|ando)$/, /^enví(o|a|as|an|e|en|es)$/, /^enviar(me|te|lo|la|los|las|le|les|nos)$/], []],
  ['cumplimiento', 'Cumplimiento', [/^cumpl\w+$/], []],
  ['nacimiento', 'Nacimiento', [/^nac(er|e|en|ió|ieron|ido|ida|idos|imiento|erá|erán|í|iste)$/, /^nazca\w*$/, /^recién$/], ['recién']],

  // ── La respuesta del ser humano ──
  ['oracion', 'Oración', [/^oraci(ón|ones)$/, /^or(ar|as|a|amos|an|é|ó|aron|aba|aban|aré|ará|arán|ando|ado|en|emos|ad)$/], []],
  ['suplica', 'Súplica', [/^s[uú]plic(a|as|o|an|ar|ó|aron|ante|antes|aba|ando|ue|uen)$/, /^rueg(o|as|a|an|ue|uen)$/, /^rog(ar|amos|ó|aron|aba|aban|ando)$/], []],
  ['alabanza', 'Alabanza', [/^alabanzas?$/, /^alab\w+$/, /^aleluya$/], ['alabastro']],
  ['canto', 'Canto', [/^cantos$/, /^cánticos?$/, /^cant(ar|a|an|en|emos|aré|ará|arán|ó|aron|aba|aban|ando|ad|ores|or)$/, /^himnos?$/], []],
  ['adoracion', 'Adoración', [ar('ador'), /^adoraci(ón|ones)$/, /^adorador(es)?$/], []],
  ['obediencia', 'Obediencia', [/^obedien\w+$/, /^obedec\w+$/, /^obedez\w+$/, /^desobed\w+$/], []],
  ['servicio', 'Servicio', [/^servicios?$/, /^servidor(a|es|as)?$/, /^sierv[oa]s?$/, /^serv(ir|imos|ía|ían|irá|irán|iré|iría|ido|irle|irlo|irles|irme|irte)$/, /^sirv(o|es|e|en|a|an|as|amos|ió|ieron|iendo)$/], []],
  ['sacrificio', 'Sacrificio', [/^sacrifici\w+$/, /^sacrific\w+$/], []],
  ['ofrenda', 'Ofrenda', [/^ofrendas?$/, /^ofrec\w+$/, /^ofrez\w+$/], []],
  ['ayuno', 'Ayuno', [/^ayun\w+$/], []],
  ['arrepentimiento', 'Arrepentimiento', [/^arrepent\w+$/, /^arrepient\w+$/, /^arrepint\w+$/], []],
  ['busqueda', 'Buscar', [/^busc\w+$/, /^busqu\w+$/], []],
  ['escucha', 'Escuchar', [/^escuch\w+$/], []],
  ['testimonio', 'Testimonio', [/^testimoni\w+$/, /^testig[oa]s?$/], []],
  ['anuncio', 'Anuncio', [/^anunci\w+$/], []],
  ['evangelio', 'Evangelio', [/^evangeli\w+$/], []],
  ['trabajo', 'Trabajo', [/^trabaj\w+$/], []],
  ['obras', 'Obras', [/^obras?$/], []],
  ['fruto', 'Fruto', [/^frutos?$/, /^fructif\w+$/], []],
  ['siembra', 'Siembra', [/^siembr\w+$/, /^sembr\w+$/, /^semillas?$/], []],
  ['cosecha', 'Cosecha', [/^cosech\w+$/], []],
  ['fuerza', 'Fuerza', [/^fuerzas?$/, /^fuertes?$/, /^fortalezas?$/, /^fortale\w+$/], []],
  ['valor', 'Valentía', [/^valientes?$/, /^valentía$/, /^valerosos?$/], []],
  ['firmeza', 'Firmeza', [/^firme(s|za|mente)?$/], []],
  ['descanso', 'Descanso', [/^descans\w+$/], []],
  ['pensamiento', 'Pensamiento', [/^pens(ar|é|ó|aron|aba|aban|ando|ado|amiento|amientos|amos|aste)$/, /^piens(o|as|a|an|e|en|es)$/], []],
  ['recuerdo', 'Recordar', [/^record(ar|é|ó|aron|aba|aban|ando|ado|amos|aré|ará|arán|aste|arás)$/, /^recuerd(o|os|as|a|an|e|en|es)$/, /^acuérd(ate|ense|ese)$/, /^acord(ó|aron|ará|aré|arse|aba|arás|arán|arte)$/, /^acuerd(o|as|a|an|e|en|es)$/, /^memoria$/], ['acuerdo']],
  ['olvido', 'Olvido', [/^olvid\w+$/], []],
  ['lucha', 'Lucha', [/^luch\w+$/], []],
  ['deseo', 'Deseo', [/^dese(o|os|as|a|an|ar|é|ó|aron|aba|aban|e|en|es|ado|ada|ados|ando|amos)$/], []],
  ['duda', 'Duda', [/^dud(a|as|ar|an|ó|aron|aba|aban|e|en|es|ando|o)$/], []],
  ['dinero', 'Dinero', [/^dinero$/], []],

  // ── El mal y la fragilidad ──
  ['pecado', 'Pecado', [/^pecados?$/, /^pecador(a|es|as)?$/, /^pec(ar|o|as|a|amos|an|é|aste|ó|aron|aba|aban|aré|ará|arán|ara|aran|ando|ado)$/, /^pequ(e|es|emos|en|é)$/], []],
  ['maldad', 'Maldad', [/^maldad(es)?$/, /^malvad[oa]s?$/, /^mal(o|a|os|as|es)?$/], []],
  ['maldicion', 'Maldición', [/^maldici\w+$/, /^maldit[oa]s?$/, /^maldec\w+$/, /^maldi[gj]\w+$/], []],
  ['mentira', 'Mentira', [/^mentir\w+$/, /^mient(o|es|e|en|a|as|an)$/, /^mintió$/, /^mintieron$/], []],
  ['engano', 'Engaño', [/^engañ\w+$/], []],
  ['orgullo', 'Orgullo', [/^orgull\w+$/], []],
  ['envidia', 'Envidia', [/^envidi\w+$/], []],
  ['codicia', 'Codicia', [/^codici\w+$/], []],
  ['violencia', 'Violencia', [/^violen\w+$/], []],
  ['guerra', 'Guerra', [/^guerras?$/, /^guerrer[oa]s?$/], []],
  ['odio', 'Odio', [/^odi(o|os|as|a|an|ar|ó|aron|aba|aban|ado|ada|ados|en|e)$/], []],
  ['venganza', 'Venganza', [/^venganzas?$/, /^veng(ar|ó|aron|ará|aré|ador|ativo|arse|arme)$/], []],
  ['enemigo', 'Enemigos', [/^enemig[oa]s?$/, /^enemistad\w*$/], []],
  ['ira', 'Ira', [/^ira$/], []],
  ['enojo', 'Enojo', [/^enoj\w+$/], []],
  ['temor', 'Temor', [/^temor(es)?$/, er('tem'), /^temeros[oa]s?$/, /^temibles?$/], ['tema', 'temas']],
  ['miedo', 'Miedo', [/^miedos?$/, /^mieditis$/], []],
  ['sufrimiento', 'Sufrimiento', [/^sufr\w+$/], []],
  ['dolor', 'Dolor', [/^dolor(es)?$/, /^dolorid[oa]s?$/, /^dolorosa?s?$/], []],
  ['angustia', 'Angustia', [/^angusti\w+$/], []],
  ['afliccion', 'Aflicción', [/^aflic\w+$/, /^aflig\w+$/], []],
  ['tristeza', 'Tristeza', [/^trist\w+$/, /^entristec\w+$/], []],
  ['llanto', 'Llanto', [/^llor\w+$/, /^llant\w+$/, /^lágrimas?$/], []],
  ['enfermedad', 'Enfermedad', [/^enferm\w+$/], []],
  ['sanacion', 'Sanación', [/^san(ar|o|a|os|as|ó|aron|ará|aré|ado|ada|ados|aba|e|en)$/, /^sán(ame|alo|anos)$/, /^cur(ar|an|ó|aron|ará|ado|ada|ados|aba|e|en|ación|aciones)$/, /^salud$/], []],
  ['hambre', 'Hambre', [/^hambr\w+$/], []],
  ['sed', 'Sed', [/^sed$/, /^sedient\w+$/], []],
  ['pobreza', 'Pobreza', [/^pobres?$/, /^pobreza$/], []],
  ['riqueza', 'Riqueza', [/^riquezas?$/, /^ric[oa]s?$/, /^enriquec\w+$/], []],
  ['esclavitud', 'Esclavitud', [/^esclav\w+$/], []],
  ['prueba', 'Prueba', [/^pruebas?$/, /^prob(ar|ó|aron|ado|ada|ados|ándo\w+)$/], []],
  ['tentacion', 'Tentación', [/^tentaci\w+$/, /^tent(ar|ó|aron|ado|ados|ador|ándo\w+|aba|a|an)$/], []],
  ['culpa', 'Culpa', [/^culpas?$/, /^culpables?$/, /^culp(ar|an|ó|aron|ado|ados)$/], []],
  ['verguenza', 'Vergüenza', [/^vergüenza\w*$/, /^avergon\w+$/, /^avergüen\w+$/, /^vergonzos\w+$/], []],
  ['castigo', 'Castigo', [/^castig\w+$/], []],
  ['juicio', 'Juicio', [/^juicios?$/, /^juzg\w+$/, /^juez$/, /^jueces$/], []],
  ['condena', 'Condena', [/^conden\w+$/], []],
  ['necedad', 'Necedad', [/^neci[oa]s?$/, /^necedad\w*$/], []],
  ['idolatria', 'Ídolos', [/^ídolos?$/, /^idol\w+$/], []],
  ['demonio', 'Demonios', [/^demonios?$/, /^diablo$/, /^endemoni\w+$/], []],

  // ── Justicia y convivencia ──
  ['justicia', 'Justicia', [/^justicias?$/, /^just[oa]s?$/, /^justamente$/, /^justific\w+$/], []],
  ['rectitud', 'Rectitud', [/^rect[oa]s?$/, /^rectitud$/, /^rectamente$/], []],
  ['honradez', 'Honradez', [/^honrad\w+$/, /^honest\w+$/], []],
  ['honor', 'Honor', [/^honor(es)?$/, /^honr(a|as|ar|an|ó|aron|ará|aré|e|en)$/], []],
  ['respeto', 'Respeto', [/^respet\w+$/], []],
  ['projimo', 'Prójimo', [/^prójimos?$/], []],
  ['amistad', 'Amistad', [/^amig[oa]s?$/, /^amistad(es)?$/], []],
  ['familia', 'Familia', [/^familias?$/], []],
  ['padre', 'Padre', [/^padres?$/], []],
  ['madre', 'Madre', [/^madres?$/], []],
  ['hijo', 'Hijos', [/^hij[oa]s?$/], []],
  ['hermano', 'Hermanos', [/^herman[oa]s?$/], []],
  ['esposos', 'Esposos', [/^espos[oa]s?$/, /^matrimonio\w*$/], []],
  ['nino', 'Niños', [/^niñ[oa]s?$/], []],
  ['joven', 'Juventud', [/^jóvenes$/, /^joven$/, /^juventud$/], []],
  ['anciano', 'Ancianos', [/^ancian[oa]s?$/, /^vejez$/], []],
  ['viuda', 'Viudas', [/^viudas?$/], []],
  ['huerfano', 'Huérfanos', [/^huérfan[oa]s?$/], []],
  ['extranjero', 'Extranjeros', [/^extranjer[oa]s?$/], []],
  ['comunidad', 'Comunidad', [/^comunidad(es)?$/], []],
  ['iglesia', 'Iglesia', [/^iglesias?$/], []],
  ['unidad', 'Unidad', [/^unidad$/, /^unid[oa]s?$/, /^reconcili\w+$/], []],
  ['pan', 'Pan', [/^pan(es)?$/], []],
  ['agua', 'Agua', [/^aguas?$/], []],
  ['fuego', 'Fuego', [/^fuegos?$/], []],
  ['pastor', 'Pastor', [/^pastor(es)?$/, /^pastorear\w*$/], []],
  ['oveja', 'Ovejas', [/^ovejas?$/, /^rebaños?$/], []],
  ['fiesta', 'Fiesta', [/^fiestas?$/, /^celebr\w+$/], []],
  ['recompensa', 'Recompensa', [/^recompens\w+$/, /^premi\w+$/], []],
  ['pureza', 'Pureza', [/^pur[oa]s?$/, /^pureza$/, /^purific\w+$/], []],
  ['cuidado', 'Cuidado', [/^cuidad[oa]s?$/, /^cuid(ar|a|an|ó|aron|ará|aré|aba|aban|e|en|es|ando)$/, /^cuíd\w+$/], []],
  ['proteccion', 'Protección', [/^proteg\w+$/, /^protej\w+$/, /^protecci\w+$/, /^protector\w*$/], []],
  ['refugio', 'Refugio', [/^refugi\w+$/], []],
  ['silencio', 'Silencio', [/^silenci\w+$/], []],
  ['lengua', 'Lengua', [/^lenguas?$/], []],
]
